# https://prettier.io/docs/en/options
printWidth: 120
tabWidth: 4
useTabs: true
semi: false
singleQuote: false
quoteProps: "consistent"
jsxSingleQuote: false
trailingComma: "none"
bracketSpacing: true
bracketSameLine: true
arrowParens: "always"
requirePragma: false
insertPragma: false
proseWrap: "never"
htmlWhitespaceSensitivity: "strict"
endOfLine: "lf"
embeddedLanguageFormatting: "auto"
singleAttributePerLine: false

overrides:
    - files: "*.md"
      options:
          useTabs: false
